LogIn / LogOut
lukaszmojek/PackagesOfFuture pull request #4
Opened 2021-12-15 00:04 UTC by lukaszmojek

2021-12-15 19:07 UTC, dblaszkiewicz requested changes
prosze wyjasnic kilka spraw inaczej nie przepuszcze hehe

2021-12-15 19:07 UTC, dblaszkiewicz commented on PackagesOfFuture.WebUI/src/app/auth/authentication.service.ts
> +    return !!localStorage.getItem(this.localStorageTokenKey)
czemu 2x wykrzykniki?

2021-12-15 19:07 UTC, dblaszkiewicz commented on PackagesOfFuture.Backend/Api/Startup.cs
> +            app.UseCors(x => x
o co z tym biega i czemu wcześniej tego nei było?

2021-12-15 19:07 UTC, dblaszkiewicz commented on PackagesOfFuture.WebUI/src/app/auth/authentication.service.ts
> +    //TODO: Think how to change that to different observable,
starczy nam usuniecie tokena

2021-12-15 19:07 UTC, dblaszkiewicz commented on PackagesOfFuture.WebUI/src/app/auth/authorization.service.ts
> +      return EMPTY
EMPTY === null ?

2021-12-15 19:07 UTC, dblaszkiewicz commented on PackagesOfFuture.WebUI/src/app/menu/menu.component.html
> +<a class="menu-item" [routerLink]="['client']">
bedziemy miec w html takie router link czy w typescripcie jakis onClick i navigate pod dany url?

2021-12-15 19:07 UTC, dblaszkiewicz commented on PackagesOfFuture.WebUI/src/app/shared/components/login/login.component.html
> +        placeholder="***** ***"
xd

2021-12-15 19:07 UTC, dblaszkiewicz commented on PackagesOfFuture.WebUI/src/app/shared/components/login/login.component.html
> +<mat-card class="flex--column card">
te wszystkie selektory zaczynajace sie od mat to jest ten angular material?

2021-12-15 19:07 UTC, dblaszkiewicz commented on PackagesOfFuture.WebUI/src/app/auth/auth.effects.ts
> +  logIn$ = createEffect(() => this.actions$.pipe(
z tymi efektami narazie Cie przepuszcze i po mergu se to przejrze bo nie kumam do konca tego

2021-12-15 23:04 UTC, lukaszmojek commented on PackagesOfFuture.WebUI/src/app/auth/authentication.service.ts
> +    //TODO: Think how to change that to different observable,
No to jest już robione, natomiast pewnie jest jakiś observable lepszy do tego zastosowania tutaj

2021-12-15 23:05 UTC, lukaszmojek commented on PackagesOfFuture.Backend/Api/Startup.cs
> +            app.UseCors(x => x
Umożliwia wykonywanie zapytań do API z wszystkich źródeł, można by ty niby wstawić po prostu adres apki angularowej i tez by działało

2021-12-15 23:06 UTC, lukaszmojek commented on PackagesOfFuture.WebUI/src/app/auth/authentication.service.ts
> +    return !!localStorage.getItem(this.localStorageTokenKey)
Sprawdza czy wyrażenie nie jest wartością nullową, czyli czy jakiś pusty string także się nie wkradł albo undefined

2021-12-15 23:06 UTC, lukaszmojek commented on PackagesOfFuture.WebUI/src/app/auth/authorization.service.ts
> +      return EMPTY
Nope, to jest pusty observable, żeby nie wyrzucać błędów ani nie przerywać subskrypcji

2021-12-15 23:07 UTC, lukaszmojek commented on PackagesOfFuture.WebUI/src/app/menu/menu.component.html
> +<a class="menu-item" [routerLink]="['client']">
routerLink

2021-12-15 23:07 UTC, lukaszmojek commented on PackagesOfFuture.WebUI/src/app/menu/menu.component.html
> +<a class="menu-item" [routerLink]="['client']">
No i pewnie guardy z przekierowaniem pewnie w TS

2021-12-15 23:07 UTC, lukaszmojek commented on PackagesOfFuture.WebUI/src/app/shared/components/login/login.component.html
> +<mat-card class="flex--column card">
Tak

2021-12-15 23:08 UTC, lukaszmojek commented on PackagesOfFuture.WebUI/src/app/auth/auth.effects.ts
> +  logIn$ = createEffect(() => this.actions$.pipe(
No i gitara xd

2021-12-15 23:08 UTC, lukaszmojek commented
Rozwiązane

2021-12-16 18:30 UTC, dblaszkiewicz approved these changes

2021-12-16 18:31 UTC, dblaszkiewicz commented
cos zjebałem xD

2021-12-16 21:34 UTC, lukaszmojek commented
Co za typ xD I tak widzę, że są konflikty, wiec możliwe, że się jeszcze Twój Approve zresetuje 🙃

2021-12-16 23:07 UTC, merged